name: Prabhat
trigger:
 branches:
    include:
      - main
pool:
 name: prabhatpool1
stages:
  - stage: buildstage
    displayName: Build stage
    jobs:
      - job: Terraformcommandsjob
        displayName: Terraform command job
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'yusufserviceconnection'
            backendAzureRmResourceGroupName: 'tata'
            backendAzureRmStorageAccountName: 'tatastorage1'
            backendAzureRmContainerName: 'tatacontainer'
            backendAzureRmKey: 'prabhat.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'



  
