
name: 'kaka'

trigger: none

pool: prabhatpool1
     
jobs:
- job: Myfirstjob 
  displayName: My first job
  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/provider.tf'
      backendServiceArm: 'yusufserviceconnection'
      backendAzureRmStorageAccountName: 'prabhatstorageacc'
      backendAzureRmContainerName: 'prabhatcontainer'
      backendAzureRmKey: 'prabhat.tfstate'

  
